language: python
python:
<<<<<<< 1299acd8780705d462cc5b6cf3454bcbc29cf0a7
=======
  - "2.7"
>>>>>>> chore(setup): Fix continuous Integration with circleci and codeclimate (#7)
  - "3.6.1"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
